### ISSUE TITLE
Is it safe to share configs

### ISSUE THREAD

**Issue by vol24pl** [lra/mackup#1396]
Are login and passwords (or any other confidential data that could be stored in app settings) saved through Mackup?

For example I’d love to share my MacBook setup with configs included through Mackup but I don’t want people to have my SourceTree repos or credentials. Am I safe to share my configs? Is that policy app specific or is it a rule of thumb?

**Comment by joshmedeski** [comment]
The short answer is "yes", Mackup might store sensitive information.

You'll have to go through what was backed up to be sure for yourself. It's hard to give a blanket answer because there are a lot of potential applications it will back up so it's better to be safe than sorry.

I personally recommend not sharing your configs in any public way.

[dotfiles.github.io](https://dotfiles.github.io/) is an example of how people have shared their configs (dotfiles) in a safe and controlled way.

**Comment by vol24pl** [comment]
Thanks for detailed answer!
