### ISSUE TITLE
Removed backup accidentally 

### ISSUE THREAD

**Issue by oaattia** [lra/mackup#1821]
First of all, thanks for this amazing tool for backing up the configs for the apps, I was trying to use this tool, and I backup (symlinked) configs using the command 

```
mackup -f backup
```
I used iCloud for backup storage, but some of the apps didn't back up the cause of permission issues, 
so I see the configs copied liked this example: 

```
.zshenv -> /Users/oabdelrahman/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.zshenv
```
The problem now I deleted the directory (backup) from cloud accidentally, and now my configs are broken.
if there is a way I can fix that again?

**Comment by lra** [comment]
You mention both google cloud and icloud, so it's confusing.
I use neither, but your only chance is to recover the files from the cloud you were using.
Mackup has not storage capability, and is only using what you tell it to use.

**Comment by oaattia** [comment]
Sorry i meant icloud, 
So i can only recover that on icloud side

**Comment by lra** [comment]
Sorry it's all on icloud, I don't have an icloud account.

**Comment by joshmedeski** [comment]
If you deleted it within the finder app, you can find the files in your Trash. If you did it in the terminal unfortunately that's a permanent action on macOS.

**Comment by mimshwright** [comment]
I have to admit, i also deleted my backups without adding them to git or anything first. I had forgotten that they were the originals now because everything is symlinked. 
Fortunately, I'm on my not-serious-work computer so I'm ok but it could have sucked.

I see there is a dry-run option (which I should have used). I wonder if you might consider adding an option copy only (not link). Maybe this is the default even and linking is an extra flag? At least that way you explicitly opt-into having these files all over your computer symlinked.

**Comment by joshmedeski** [comment]
@mimshwright oh no! Glad it wasn't a huge loss. 

The copy-only flag is an interesting idea, but changes to those copied files wouldn't affect your applications and could create confusion and frustrate users who misuse it (I DON'T recommend we change the default behavior, this would be optional behavior).
