### ISSUE TITLE
Support for the Apple Dock

### ISSUE THREAD

**Issue by lucasff** [lra/mackup#1825]
Should be enough as syncing  Library/Preferences/com.apple.dock.plist and running
```
defaults read $HOME/Library/Preferences/com.apple.dock.plist
killall Dock
```

**Comment by devnoname120** [comment]
@lra Would you be open to merge such a feature? I can do a pull request

**Comment by joshmedeski** [comment]
This is entirely possible. You can open a PR to support this. If you're unsure how to contribute let me know and I can do it.

**Comment by mimshwright** [comment]
FYI, I've had issues with backing up and symlinking the Dock because Dock is always running and the OS immediately replaces the plist file as soon as you delete it. The result is always a new dock.plist with default settings. So perhaps it can be done while the user is logged out by using a different user or SSH or something?

But hopefully someone knows another way to do this!

**Comment by lra** [comment]
Yes, no way this can be done without Mackup having its own sync file system.
