### ISSUE TITLE
[BUG] BE ALERT TO DATA LOSS

### ISSUE THREAD

**Issue by nathan-deng-ai** [lra/mackup#1859]
"Backup" should mean "copy" and should not make any changes to the original files and should not cause any possibility of data loss.

This software actually moves the source files to the configuration directory and then creates a symbol link, which is a serious violation of the "backup principle".

If users are not aware of this (and they generally are not) and place the configuration directory on an external storage or unstable network drive thinking that the backup act is one-time and has no side effects, they will lose all their software configuration and have difficulty restoring it with the restore or uninstall parameters that come with the software.

This is a serious design problem.

**Comment by lra** [comment]
There is a warning on the CLI.
It's explained in the doc.
It's useful for the huge majority of users for years the way it is.
If you think there is something to do better, please do a PR.

**Comment by lra** [comment]
Adding more context:
- Mackup was originally made for Dropbox, which is versioned, you cannot possibly lost a file with it
- Later, people asked me to support other storage engines, so I added them despite their sub-par features (most of them lack versioning). The solution to your problem is to remove support for any engine that is not versioned. This would remove a useful tool for tons of people just because a few messed up.
- Mackup is never deleting any file, to lose a file you have to: 1. Use a non versioned storage 2. Run `mackup backup` 3. explicitly delete the files in the storage that the user explicitly stated as a backup (again, Mackup defaults to dropbox).

As I said, warnings are there, and I'm not a fan of being part of the popup creators that warn about every action on a computer: this just lowers the bar of UX to match mainstream. Mackup is still a CLI so it's definitely not mainstream. If I ever do a GUI, then it will more explicit about this.

**Comment by lra** [comment]
This is not a transfer. This is a linking, but very few know what it means.

**Comment by Blackilykat** [comment]
Sorry for replying under an old issue, but I just ran into this problem. I was checking out the tool and expected it to copy over the configs, and quickly deleted the backup directory once I realized it's not what I was looking for. I then found out I just deleted my configs when I opened a new terminal and my shell and terminal emulator configs weren't there anymore.
Luckily mine were pretty short and a lot of my programs weren't supported, but I heavily suggest rethinking the decision to close this.

There may have been a warning in the CLI but I do not remember seeing one. Anything that could cause data loss should be the very first thing you notice when running a program, probably getting confirmation as well. While this does not directly cause data loss, false assumptions made about the program do.

To be clear: I'm not suggesting to change a current system. I'm suggesting there should be a hard to miss warning when running the program to make sure no one skims over it like I did.
