### ISSUE TITLE
External application repositories

### ISSUE THREAD

**Issue by fazibear** [lra/mackup#1905]
There is lot of "Add ..." PRs. Maybe it's worth to move app configs to separate repo and add support for external repos?

This will separate mackup and app configs. Other devs could develop apps config on tier own?

**Comment by joshmedeski** [comment]
All those PRs have been easy to create, review, and merge so far. Plus, it would complicate the process of deploying new versions of `mackup` if we had to manage separate repos. I don't recommend we separate them.

You could create a repo of your own custom configs and clone it to `~/.mackup` to maintain your own separate configurations from the [supported applications](https://github.com/lra/mackup#supported-applications). But I'd argue contributing to the repo is better because others may be using the same applications as you.

We encourage people add new applications to mackup! Hope that helps.
