### ISSUE TITLE
Copying settings, as opposed to linking?

### ISSUE THREAD

**Issue by vitorgalvao** [lra/mackup#195]
I’ve been thinking about this option lately. I’ve personally had my fair share of issues caused by the way `mackup` works by default (making links to a dropbox directory), whether by having more than one computer logged on at the same time, changes to `mackup` itself, or some other reason. I’ve also seen some other open *issues* with problems that would not occur would it not be for settings being symlinked, as opposed to copied over.

How many times do users change app settings, really? Wouldn’t the extra (small) trouble of running a command when updating settings be a more than acceptable price to pay for improved stability? It would also provide some features for free, like [support for MAS apps](https://github.com/lra/mackup/issues/154).

Now, I certainly understand that would be a big change to this tool (that a lot of people use), so I’m looking for your input on this, @lra, is this something you’d be willing to consider?

**Comment by mike-hearn** [comment]
I'd like to +1 this.

I use Mackup to backup my CodeKit license - this is the only thing I need backed up, with the purpose that when I `mackup restore`, it automatically adds the CodeKit license file so I don't need to re-enter my information.

The major downside here is that the license plist file also contains every other preference setting, including *window size*, so the file is getting overwritten constantly. This wastes Dropbox cycles, makes my "recent changes" pretty irrelevant, and so on. Essentially I don't care about the settings being constantly synced, I'd just like the license plist to be backed up once when I run `mackup backup`, and to be copied back to the proper place when I run `mackup restore`.

My ideal solution would be something like this:

```
[configuration]
copy = true
```

- On running `mackup backup` it just does a `cp` instead of an `ln`.
- On running `mackup restore` it does another `cp` instead of an `ln`.

I definitely think it's a common use-case for users to potentially want to back-up items (so they can be restored later), but *not* necessarily want them being persistently synced.

**Comment by aristidesfl** [comment]
I also have this problem of Dropbox always syncing. Another offending application is Karabiner which causes a file update every time it is used.

**Comment by lra** [comment]
> However, isn't backup/restore + uninstall = copy?

Yes

**Comment by vitorgalvao** [comment]
>> However, isn't backup/restore + uninstall = copy?

> Yes

No really, no. Copying allows [possibilities that are not available with linking](https://github.com/lra/mackup/issues/154), and are thus not available with backup/restore + uninstall. Were it the same thing, this wouldn’t still be an issue.

**Comment by lra** [comment]
right

**Comment by lra** [comment]
Let's do it https://github.com/lra/mackup/issues/613
