### ISSUE TITLE
Remove Quicklook support

### ISSUE THREAD

**Issue by ponychicken** [lra/mackup#414]
Quicklook plugins are hardly config files but actual executables. I think tools like brew cask are better suited for organizing them.

**Comment by lra** [comment]
I don't have any so I can't speak here. Any other user feedback?

**Comment by acusti** [comment]
I wouldn’t mind mackup backing up my QuickLook plugins (sounds practical for bootstrapping a new machine), but I’d also be happy continuing to manage them with homebrew-cask.

That said, I originally used `brew cask` myself to install my QuickLook plugins (which I discovered via [this repo](https://github.com/sindresorhus/quick-look-plugins)). Homebrew-cask leaves the existing `~/Library/QuickLook` directory and adds the individual `.qlgenerator` files to the folder as symlinks. My QuickLook plugins then stopped working after mackup took them over. I have to manually remove or rename the mackup `Quicklook` symlink (incidentally, it should be camel case, i.e. `QuickLook`) and restore my previous version of the folder, then run `qlmanage -r` in order to get them working again. And I have confirmed that the issue is specific to the plugins that were installed by `brew cask`, because I had one additional QuickLook plugin that I manually installed by copying it to the QuickLook folder, and that plugin still worked with mackup’s symlinked folder.

Maybe mackup could detect if the QuickLook plugins are already being managed by brew cask before taking over in order to avoid breaking anything? I don’t really have any idea what the best solution is. I suppose the simplest thing is to just remove support as @ponychicken suggests, but I’m not sure that’s ideal.

**Comment by revolter** [comment]
@ponychicken, @acusti, You can manually ignore by creating a `.mackup.cfg` file with this content:

    [applications_to_ignore]
    quicklook

**Comment by acusti** [comment]
@revolter Nice! I just set up a new computer recently and couldn’t figure out why my quicklook plugins weren’t working, then I realized it was from this issue. Thanks for the tip!

**Comment by revolter** [comment]
@acusti, You're welcome! I think that this issue can be closed for now.

**Comment by lra** [comment]
You don't think we should remove their support by default?

**Comment by revolter** [comment]
As far as I understood, `mackup` breaks `Quicklook` only if the plugins are installed using `brew cask`, so for the users who don't use `brew cask` it doesn't break anything. And giving the fact that one can simply disable it, I don't see why it should be removed. Correct me if I'm wrong.

**Comment by lra** [comment]
ok make sense.
