### ISSUE TITLE
What is the use of temp_file?

### ISSUE THREAD

**Issue by Timidger** [lra/mackup#469]
In `mackup.py`, the Mackup class has an attribute called `temp_folder`. What is this temporary folder used for? A quick grep through the code base reveals that it doesn't seem to do anything: 
![2015-02-13-221505_636x572_scrot](https://cloud.githubusercontent.com/assets/3515754/6198431/8dc4aea0-b3ce-11e4-9a08-4e8e6c6af65a.png)

Is it necessary to have this attribute?

**Comment by lra** [comment]
At some point, I'd like Mackup to be _transactional_. Instead of changing files directly, it would make a copy of the files in some isolated area (the temp folder), try doing the work there, and if all is ok, apply the same on the real files. If any failure in the middle of the work, it would just erase the temp folder, and the original files would not be touched.

I also wanted to know if creating/deleting this temp folder would generate problems on some user's weird config, apparently nobody complains, and keeping this code make sure we can do the transactional feature without worrying about the "where do we put the files?" part.

Only the temp folder creation/deletion has been implemented yet ;)

**Comment by Timidger** [comment]
Ah, I see. Thank you very much!
