### ISSUE TITLE
Will it move files which are already symlynks?

### ISSUE THREAD

**Issue by svetlyak40wt** [lra/mackup#501]
I'm using a [dotfiler](https://github.com/svetlyak40wt/dotfiler) to manage some of my dotfiles such as emacs and zsh configs for example, and dotfiler keeps them in a separate directory (as mackup do) and makes symlink.

So, I want to backup with mackup only my OSX apps settings. Is it possible???

**Comment by lra** [comment]
Of course, you can tell Mackup to only sync the applications you want: https://github.com/lra/mackup/tree/master/doc#applications

**Comment by gvaughn** [comment]
I just ran into this too. I love the idea of mackup, but mostly for the Library/* files. I manage my dotfiles separately. I initially tried a `mackup backup` then a `mackup restore` and my previously symlinked files were no longer symlinked. I did create the .mackup.cfg file to exclude the relevant files and eventually got things straightened out.

However, if mackup were to detect during the backup that these files were already symlinks, it would have saved me some time in the initial setup. I guess this can be a feature request at this point.

**Comment by rocketnova** [comment]
I second @gvaughn. My previously symlinked files were no longer symlinked after I ran `mackup restore` which kind of sucks. It would be really nice if there was some kind of warning on the command line or in the README about this.

**Comment by lra** [comment]
> It would be really nice if there was some kind of warning on the command line or in the README about this.

We can't have a warning for every file mackup wants to move, this would drive people insane, as they are already tired of the existing messages. See https://github.com/lra/mackup/pull/493

Regarding replacing symlinks mackup does not own during uninstall, the problem is that right now mackup works accross all the apps by default. This behavior is gonna change in https://github.com/lra/mackup/issues/614
