### ISSUE TITLE
how to backup dotfiles for root user?

### ISSUE THREAD

**Issue by shoaly** [lra/mackup#666]
when i run mackup backup, it prompt:
 Running Mackup as a superuser is useless and dangerous. Don't do it!

I am wondering how I can backup for root?

**Comment by Joshfindit** [comment]
Suggestion 1: change the file permissions on the file that you want to backup
Suggestion 2: hard link the root file to a location that's available to the user

**Comment by lra** [comment]
suggestion 3: don't ever use root as a user.

**Comment by piotrraczynski** [comment]
I generally agree with comment above and below string (not being able to run as root):

https://github.com/lra/mackup/blob/755095e590deab8f4a2875e36800a021094f683d/mackup/mackup.py#L34

However there are cases that I have to use root account (due to specific OS or application design constrains, embedded systems and specialized units) and it would be nice to have my same setup in those cases.

before generating pull request, would you even consider accepting optional e.g. --root flag (with additional warning message)?

**Comment by lra** [comment]
I guess that's fine if it's an explicitly stated argument.
