### ISSUE TITLE
Skype GIFs backed up

### ISSUE THREAD

**Issue by altosaar** [lra/mackup#705]
In my 'recent' dropbox items are hundreds of gifs mackup has backed up from skype. Would be nice to disable having these backed up :)

**Comment by lra** [comment]
You need to improve https://github.com/lra/mackup/blob/master/mackup/applications/skype.cfg

**Comment by anantshri** [comment]
Hey Folks, I am new to this is there a simpler guide on how to write cfg's also what i am getting is the following folder needs to be excluded.

inside the backup folder : Library/Application Support/Skype/<username>/media_messaging/emo_cache/ <- this folder needs to be excluded from the backup. But considering we are syncing the whole folder via symlink this sounds like a bit of work.

All i can think of is backing up all folders except this one but since it has a username element to it, this might not be as simple as just quoting it out

**Comment by moltar** [comment]
Yes, super annouying. Clogs up the whole Google Drive sync with a bunch of useless files.

All of them named something like:

`^003AFEAFC0BBF745958FE4C77B695B0A493D4A48498992AF55^pdefault_5b000c95-f530-4a7f-b302-842675aaa249_distr`

All are useless GIFs, MP4s and PNGs. I don't even know why Skype comes bundled with this crap.

**Comment by moltar** [comment]
The full location is:

`Library/Application Support/Skype/%SKYPE_USERNAME%/media_messaging/emo_cache`

**Comment by moltar** [comment]
For now I simply deleted everything inside that folder and then changed permissions to make it non-writable. So far I can still see normal emoticons (smiles), and Skype has not complained.

**Comment by lra** [comment]
can someone come up with a PR? I don't use Skype.

**Comment by moltar** [comment]
I could, I guess. I'm just not sure of the syntax. Is there a way to blacklist a certain dir? Or do we just need to explicitly list every dir that is good?

**Comment by lra** [comment]
> Is there a way to blacklist a certain dir?

No
