### ISSUE TITLE
Permissions not preserved

### ISSUE THREAD

**Issue by tewe** [lra/mackup#836]
This is my `~/Library/Application Support/BBEdit/Text Filters` before and after using mackup:

	-rwxr-xr-x@  1 staff   466 Jul 31  2015
	-rwxr-xr-x@  1 staff    31 Sep 15  2015
	-rw-r--r--   1 staff  1006 May 15 09:13
	-rwxr-xr-x   1 staff    94 Jul 31  2003
	-rwxr-xr-x@  1 staff   207 Jul 31  2015
	-rwxr-xr-x@  1 staff   141 Jan 31 12:53

	-rw-------@  1 staff   466 Jul 31  2015
	-rw-------@  1 staff    31 Sep 15  2015
	-rw-------@  1 staff  1006 May 15 09:13
	-rw-------@  1 staff    94 Jul 31  2003
	-rw-------@  1 staff   207 Jul 31  2015
	-rw-------@  1 staff   141 Jan 31 12:53

Obviously they no longer work:

> The script being run is neither a Unix executable nor a text file (application error code: 13309)

As far as I see mackup uses `shutil.copytree`, which should preserve permissions, and did preserve the mtime, so not sure what happened.

**Comment by lra** [comment]
https://github.com/lra/mackup/blob/master/mackup/utils.py#L112
We do chmod all the synced files because there are supposed to be configuration files, and some files have keys and credentials.
As we copy the files to 3rd party software (e.g. dropbox) and some of them apply stupid permissions to those files, we had to go the conservative route (0600 on files and 0700 on folders).

This is not fixable as it depends on the behavior of those cloud storage services, and they are not consistent.

Sorry, but the only way here is to not sync executable files, just config files. I suggest removing those files from the list of files to sync.

**Comment by tewe** [comment]
I'd consider macros part of the configuration, and I'd rather cut off broken storage services than mess with user data.

Would a `~/.mackup/bbedit.cfg` override the one you ship?

**Comment by tewe** [comment]
> Would a ~/.mackup/bbedit.cfg override the one you ship?

Yes.
