### ISSUE TITLE
Add a flag for not linking automatically

### ISSUE THREAD

**Issue by jymoulin** [lra/mackup#859]
Hi,

The default usage (make a link to a 'remote' directory) is not a backup but a synchronization tool. If you change your original file, as this is only a link, you also change the backup file. You cannot recover it.

It can be nice to add a flag to choose between a link or a copy, to provide a real backup.

Thanks !
Best,
jym

**Comment by xkef** [comment]
I don't see why a simple script like below does not achieve the  thing (then rsync back would do it imho):

```
#!/bin/bash

# make backupdir
mkdir backup_$(date +%Y_%m_%d)
cd backup_$(date +%Y_%m_%d)

get_mackup_resources() {
  git clone https://github.com/lra/mackup
  mv mackup/mackup/applications .
  rm -fr mackup 
  for d in applications/*.cfg ; do
    cat $d | sed -r '/^\s*$/d' | \
             sed -r '/^\[/d' | \
             sed -r '/^name/d' | \
             sed -r '/^#/d' >> apps.txt
  done
  rm -fr applications
  cat apps.txt | sort > apps_sorted.txt
}

# copy everything to backupdir
get_mackup_resources
mkdir mackup
rsync -aLkru ~/ \
  --files-from=apps_xkef_sorted.txt \
  --ignore-errors \
  mackup/
```

**Comment by KevinVlaanderen** [comment]
Morning,

Like the original poster, I'd also be interested in a way to copy instead of link. To make the case, I'll outline my setup.

My primary use case is backing up instead of syncing, for the purpose of facilitating a system restore in case I move to a new system or something happens to my machine.

My approach to this use case is that I want to provision my machine from original sources as much as possible, in an automated fashion as much as possible. Applications should be installed through their normal channels (e.g. brew), repos should be cloned from their origins (e.g. Github), data should be available through e.g. Dropbox. And for configuration files, Mackup fills in the gap.

I currently have a task running every day that, amongst other things, does the following:
- Dump all installed brew applications to a file
- Run mackup to backup any new application config files
- Push everything to a private git repository

Mackup's approach, with per-application whitelists, is a good fit with the above. However, linking iso copying is rather intrusive, as it limits my ability to move things around. Instead, I would prefer a side-effect free mechanism while still employing the whitelisting mechanism.

I'd be happy to discuss this further, and if the discussion leads to a solid idea of how this might work and what the impact would be, I am very willing to implement this and send in a PR.

**Comment by lra** [comment]
Yes, TODO is https://github.com/lra/mackup/issues/613
