### ISSUE TITLE
Copying > Symlinking by default

### ISSUE THREAD

**Issue by vecmezoni** [lra/mackup#905]
I've tried to use mackup with current dotfiles git repo and decided to ignore some useless configs. I've ignored them and deleted them and decided to make `git clean -fd` to start everything over.
Suddenly i've realised that every dotfile was symlinked (not copied), so i've accidentally deleted all my dotfiles. 

Would not it be better to copy files by default? If not, would not it be better to mention this somewhere in the Readme (i don't see any mention of this behaviour).

**Comment by vecmezoni** [comment]
Looks like a duplicate https://github.com/lra/mackup/issues/859

**Comment by MadeOfMagicAndWires** [comment]
From the README
> ## Bullsh*t, what does it really do to my files
> 
> Let's take `git` as an example. Your settings for `git` are saved in your home
> folder, in the `.gitconfig` file.
> 
> ### Backup
> 
> If you have Dropbox, these things happen when you launch `mackup backup`:
> 
> 1. `cp ~/.gitconfig ~/Dropbox/Mackup/.gitconfig`
> 1. `rm ~/.gitconfig`
> 1. `ln -s ~/Dropbox/Mackup/.gitconfig ~/.gitconfig`
> 
> Now your `git` config is always backed up and up to date on all your workstations.

It symlinks files because the point is to sync a single folder between machines once, and then to forget it. If it copied files you'd have to manually overwrite your older copies every time you update something on one machine.

**Comment by lcardito** [comment]
@MadeOfMagicAndWires I understand what you're saying, however I think there's the use case of a simple backup/restore scenario that might be nice to support.

I am personally using this tool as a backup tool and only really restore when I wipe clean the mac and re-install everything from scratch.

The option to copy rather than linking would simplify things and avoid accidental delete of files you need.

Any change an option flag could be added here?

Thanks!

**Comment by MadeOfMagicAndWires** [comment]
I feel like the main usecase scenario is always going to be synchronizing setups as that's what mackup was made to do. There are plenty of apps that simply backup files and as mentioned copying rather than symlinking would complicate synching.

You're of course more than welcome to use mackup for your usecase but I do think that you might be better served by another tool. 

Regardless, if you still feel like you'd rather have copy functionality in mackup please move further discussion to #859. I'm closing this, as this is indeed a duplicate.
